USE HR;

-- CREATE TABLE EMPLOYEE
CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID int PRIMARY KEY,
	EMPLOYEE_FNAME varchar(40) NOT NULL,
	EMPLOYEE_LNAME varchar(40) NOT NULL,
	EMPLOYEE_HEREDATE date,
	EMPLOYEE_TITLE varchar(30)
)

-- SELECT EMPLOYEE
SELECT * FROM EMPLOYEE

--INSERT INTO EMPLOYEE
INSERT INTO EMPLOYEE
VALUES (03373, 'Marco', 'Polo', GETDATE(), 'Discover'),
(08278, 'Franklin', 'Johnson', GETDATE(), 'Agent'),
(07842, 'Patrica', 'Richards', GETDATE(), 'DBA'),
(12489, 'Katrina', 'Jade', GETDATE(), 'Programmer')


--CHANGE TABLE EMPLOYEE
ALTER TABLE EMPLOYEE 
ADD CONSTRAINT DF_TITLE DEFAULT N'unknown' FOR EMPLOYEE_TITLE

--INSERT INTO EMPLOYEE
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_FNAME, EMPLOYEE_LNAME, EMPLOYEE_HEREDATE)
VALUES (12345, 'Nicole', 'Anistone', GETDATE())


--CREATE TABLE SKILL
CREATE TABLE SKILL(
	SKILL_ID int PRIMARY KEY IDENTITY(100, 10),
	SKILL_NAME varchar(50) NOT NULL,
	SKILL_DESCRIPTION varchar(200),
	CONSTRAINT check_id CHECK(SKILL_ID>99 AND SKILL_ID<221)
)

--SELECT SKILL
SELECT * FROM SKILL

--INSERT INTO SKILL
INSERT INTO SKILL(SKILL_NAME, SKILL_DESCRIPTION)
VALUES ('BASIC DATABASE MANAGEMENT', 'CREATE AND MANAGE DATABASE'),
('BASIC WEB DESIGN','CREATE AND MAINTAINE HTML'),
('ADVENCED SPREADSHEETS','USE OF ADVENCED FUNCTIONS')

--CREATE TABLE CERTIFIED
CREATE TABLE CERTIFIED (
	EMLOYEE_ID INT FOREIGN KEY REFERENCES EMPLOYEE(EMPLOYEE_ID),
	SKILL_ID INT FOREIGN KEY REFERENCES SKILL(SKILL_ID),
	CERTIFIED_DATE DATE
)

--SELECT CERTIFIED
SELECT * FROM CERTIFIED

--INSERT INTO CERTIFIED
INSERT INTO CERTIFIED
VALUES (02345, 100, '2/14/2002'),
(12345, 120, '2/14/2002')