-- CREATE DATABASE STORE
CREATE DATABASE STORE

--USE THE STORE DATABASE
USE STORE;

--CREATE TABLE EMPLOYEE
CREATE TABLE EMPLOYEE(
	EMP_CODE INT PRIMARY KEY IDENTITY(1,1),
	EMP_TITLE VARCHAR(3) DEFAULT 'UNKNOWN',
	EMP_LNAME VARCHAR(20),
	EMP_FNAME VARCHAR(20),
	EMP_INITIAL VARCHAR(10),
	EMP_DOB DATE,
	STORE_CODE INT FOREIGN KEY REFERENCES STORE(STORE_CODE) DEFAULT 3
)

--SELECT EMPLOYEE
SELECT * FROM EMPLOYEE

--INSERT INTO EMPLOYEE
INSERT INTO EMPLOYEE(EMP_TITLE, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_DOB)
VALUES('Mr', 'Williamson', 'John', 'W', '21-May-64');

INSERT INTO EMPLOYEE
VALUES( 'Ms', 'Ratula', 'Nancy', '', '09-Feb-69', 2),
('Ms', 'Greenboro', 'Lottie', 'R', '02-Oct-61', 1)

--CREATE TABLE STORE
CREATE TABLE STORE(
	STORE_CODE INT PRIMARY KEY,
	STORE_NAME VARCHAR(30),
	STORE_YTD_SALES FLOAT CONSTRAINT ST_SALES CHECK(STORE_YTD_SALES>0),
	REGION_CODE INT FOREIGN KEY REFERENCES REGION(REGION_CODE),
	EMP_CODE INT 
)

--SELECT STORE
SELECT * FROM STORE;

--INSERT INTO STORE
INSERT INTO STORE VALUES(1, 'Access Junction',10003455.76,2,8),
(2, 'Database Corner', 1421987.39, 2, 12);

INSERT INTO STORE VALUES(3, 'Tuple Charge', 986783,1 ,7)

--CREATE TABLE REGION
CREATE TABLE REGION(
	REGION_CODE INT PRIMARY KEY,
	REGION_DESCRIPT VARCHAR(5)
)

--SELECT REGION
SELECT * FROM REGION;

--INSERT INTO REGION
INSERT INTO REGION VALUES(1, 'East'),
(2, 'Weast')